[package]
name = "softpilot-plugin-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["component-validation"]
component-validation = ["dep:wasmtime"]

[dependencies]
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
softpilot-core = { path = "../softpilot-core" }
thiserror.workspace = true
wasmtime = { workspace = true, optional = true }
zip.workspace = true

[lints]
workspace = true
